//
//  DeliveryChecklistExport.swift
//  KWh Gas Companion
//
//  Turns a finished inspection into something you can hand to a delivery
//  advisor — plain text for a message, PDF for the paper trail.
//
//  Swift 6 • iOS 17+
//

import Foundation
#if canImport(UIKit)
import UIKit
#endif

public enum DeliveryChecklistExport {

    // MARK: - Plain text

    public static func plainText(_ run: DeliveryChecklistRun) -> String {
        var lines: [String] = []

        lines.append(run.displayTitle.uppercased())
        lines.append(String(repeating: "=", count: max(8, run.displayTitle.count)))

        if !run.vehicle.isEmpty { lines.append("Vehicle: \(run.vehicle)") }
        if !run.vin.isEmpty { lines.append("VIN: \(run.vin)") }
        if let date = run.deliveryDate {
            lines.append("Delivery: \(date.formatted(date: .long, time: .omitted))")
        }
        lines.append("Inspected: \(Date().formatted(date: .long, time: .shortened))")
        lines.append("")
        lines.append("Checked \(run.checkedCount) of \(run.totalCount) items · \(run.passCount) good · \(run.flaggedCount) flagged")
        lines.append("")

        let flagged = run.flaggedItems
        if !flagged.isEmpty {
            lines.append("ITEMS NEEDING ATTENTION")
            lines.append(String(repeating: "-", count: 23))
            for (item, state) in flagged {
                lines.append("[\(state.status.title)] \(item.category.rawValue) — \(item.title)")
                let note = state.note.trimmingCharacters(in: .whitespacesAndNewlines)
                if !note.isEmpty { lines.append("    Note: \(note)") }
                if !state.photoFilenames.isEmpty {
                    let count = state.photoFilenames.count
                    lines.append("    \(count) photo\(count == 1 ? "" : "s") attached")
                }
                if let updated = state.updatedAt {
                    lines.append("    Recorded: \(updated.formatted(date: .abbreviated, time: .shortened))")
                }
                lines.append("")
            }
        }

        lines.append("FULL RESULTS")
        lines.append(String(repeating: "-", count: 12))

        for category in DeliveryChecklistCategory.allCases {
            let items = run.items(in: category)
            guard !items.isEmpty else { continue }

            lines.append("")
            lines.append("\(category.rawValue) — \(run.checkedCount(in: category))/\(run.totalCount(in: category))")

            for item in items {
                let state = run.state(for: item.id)
                lines.append("  \(marker(for: state.status)) \(item.title)")
                let note = state.note.trimmingCharacters(in: .whitespacesAndNewlines)
                if !note.isEmpty { lines.append("      \(note)") }
            }
        }

        lines.append("")
        lines.append("Generated by KWh Gas Companion.")

        return lines.joined(separator: "\n")
    }

    private static func marker(for status: DeliveryItemStatus) -> String {
        switch status {
        case .unchecked: return "[ ]"
        case .pass:      return "[x]"
        case .attention: return "[!]"
        case .recheck:   return "[~]"
        }
    }

    /// Writes the text export to a temp file so it can be shared as a document
    /// rather than pasted into the body of a message.
    public static func textFileURL(_ run: DeliveryChecklistRun) -> URL? {
        let text = plainText(run)
        let name = sanitizedFilename(run.displayTitle) + ".txt"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(name)
        do {
            try text.write(to: url, atomically: true, encoding: .utf8)
            return url
        } catch {
            return nil
        }
    }

    static func sanitizedFilename(_ raw: String) -> String {
        let cleaned = raw
            .components(separatedBy: CharacterSet.alphanumerics.union(CharacterSet(charactersIn: " -_")).inverted)
            .joined()
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: " ", with: "-")
        return cleaned.isEmpty ? "delivery-inspection" : cleaned
    }
}

// MARK: - PDF

// Internal rather than public: these take `DeliveryChecklistStore`, which is
// internal like every other store in the app.
#if canImport(UIKit)
extension DeliveryChecklistExport {

    /// US Letter, with photos embedded under the item they belong to.
    @MainActor
    static func pdfData(_ run: DeliveryChecklistRun, store: DeliveryChecklistStore) -> Data {
        // Load every photo up front. The renderer's drawing closure is not
        // main-actor isolated, so the store can't be reached from inside it —
        // and doing file I/O mid-render would be the wrong shape anyway.
        var photos: [String: UIImage] = [:]
        for state in run.states.values {
            for filename in state.photoFilenames where photos[filename] == nil {
                let url = store.photoURL(filename, runID: run.id)
                guard let data = try? Data(contentsOf: url),
                      let image = UIImage(data: data) else { continue }
                photos[filename] = image
            }
        }

        let pageWidth: CGFloat = 612
        let pageHeight: CGFloat = 792
        let margin: CGFloat = 48
        let contentWidth = pageWidth - margin * 2

        let renderer = UIGraphicsPDFRenderer(
            bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        )

        return renderer.pdfData { context in
            var cursor: CGFloat = margin
            var pageStarted = false

            func newPage() {
                context.beginPage()
                cursor = margin
                pageStarted = true
            }

            /// Draws `text`, wrapping to the content width and paginating.
            func draw(_ text: String, font: UIFont, color: UIColor = .black, indent: CGFloat = 0, spacing: CGFloat = 4) {
                if !pageStarted { newPage() }

                let paragraph = NSMutableParagraphStyle()
                paragraph.lineBreakMode = .byWordWrapping

                let attributes: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: color,
                    .paragraphStyle: paragraph
                ]

                let width = contentWidth - indent
                let bounding = (text as NSString).boundingRect(
                    with: CGSize(width: width, height: .greatestFiniteMagnitude),
                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                    attributes: attributes,
                    context: nil
                )

                if cursor + bounding.height > pageHeight - margin { newPage() }

                (text as NSString).draw(
                    with: CGRect(x: margin + indent, y: cursor, width: width, height: bounding.height),
                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                    attributes: attributes,
                    context: nil
                )
                cursor += bounding.height + spacing
            }

            func rule(_ color: UIColor = UIColor.black.withAlphaComponent(0.18)) {
                if !pageStarted { newPage() }
                if cursor + 12 > pageHeight - margin { newPage() }
                let path = UIBezierPath()
                path.move(to: CGPoint(x: margin, y: cursor))
                path.addLine(to: CGPoint(x: pageWidth - margin, y: cursor))
                color.setStroke()
                path.lineWidth = 0.5
                path.stroke()
                cursor += 10
            }

            func drawPhotos(_ filenames: [String], indent: CGFloat) {
                let thumbHeight: CGFloat = 110
                let spacing: CGFloat = 8
                var x = margin + indent

                for filename in filenames.prefix(6) {
                    guard let image = photos[filename] else { continue }

                    let ratio = image.size.width / max(image.size.height, 1)
                    let width = min(thumbHeight * ratio, contentWidth / 2)

                    if x + width > pageWidth - margin {
                        x = margin + indent
                        cursor += thumbHeight + spacing
                    }
                    if cursor + thumbHeight > pageHeight - margin {
                        newPage()
                        x = margin + indent
                    }

                    image.draw(in: CGRect(x: x, y: cursor, width: width, height: thumbHeight))
                    x += width + spacing
                }

                cursor += thumbHeight + spacing
            }

            newPage()

            // ── Header ───────────────────────────────────────────────
            draw(run.displayTitle, font: .boldSystemFont(ofSize: 22), spacing: 6)

            var meta: [String] = []
            if !run.vehicle.isEmpty { meta.append(run.vehicle) }
            if !run.vin.isEmpty { meta.append("VIN \(run.vin)") }
            if let date = run.deliveryDate { meta.append(date.formatted(date: .long, time: .omitted)) }
            if !meta.isEmpty {
                draw(meta.joined(separator: "  ·  "), font: .systemFont(ofSize: 11), color: .darkGray, spacing: 2)
            }
            draw(
                "Inspected \(Date().formatted(date: .long, time: .shortened))",
                font: .systemFont(ofSize: 10),
                color: .gray,
                spacing: 10
            )
            rule()

            // ── Summary ──────────────────────────────────────────────
            draw(
                "\(run.checkedCount) of \(run.totalCount) items checked  ·  \(run.passCount) good  ·  \(run.flaggedCount) flagged  ·  \(run.photoCount) photos",
                font: .boldSystemFont(ofSize: 12),
                spacing: 12
            )

            // ── Flagged first ────────────────────────────────────────
            let flagged = run.flaggedItems
            if !flagged.isEmpty {
                draw("Items needing attention", font: .boldSystemFont(ofSize: 15), spacing: 8)

                for (item, state) in flagged {
                    draw(
                        "\(state.status.title.uppercased())  ·  \(item.category.rawValue)",
                        font: .boldSystemFont(ofSize: 9),
                        color: state.status == .attention ? .systemOrange : .systemBlue,
                        spacing: 2
                    )
                    draw(item.title, font: .boldSystemFont(ofSize: 12), spacing: 2)

                    let note = state.note.trimmingCharacters(in: .whitespacesAndNewlines)
                    if !note.isEmpty {
                        draw(note, font: .systemFont(ofSize: 11), color: .darkGray, indent: 10, spacing: 4)
                    }
                    if !state.photoFilenames.isEmpty {
                        drawPhotos(state.photoFilenames, indent: 10)
                    }
                    rule()
                }
                cursor += 6
            }

            // ── Full results ─────────────────────────────────────────
            draw("Full results", font: .boldSystemFont(ofSize: 15), spacing: 8)

            for category in DeliveryChecklistCategory.allCases {
                let items = run.items(in: category)
                guard !items.isEmpty else { continue }

                draw(
                    "\(category.rawValue)  —  \(run.checkedCount(in: category))/\(run.totalCount(in: category))",
                    font: .boldSystemFont(ofSize: 12),
                    spacing: 4
                )

                for item in items {
                    let state = run.state(for: item.id)
                    let color: UIColor
                    switch state.status {
                    case .unchecked: color = .gray
                    case .pass:      color = .black
                    case .attention: color = .systemOrange
                    case .recheck:   color = .systemBlue
                    }

                    draw(
                        "\(marker(for: state.status)) \(item.title)",
                        font: .systemFont(ofSize: 10.5),
                        color: color,
                        indent: 8,
                        spacing: 1
                    )

                    let note = state.note.trimmingCharacters(in: .whitespacesAndNewlines)
                    if !note.isEmpty {
                        draw(note, font: .italicSystemFont(ofSize: 9.5), color: .darkGray, indent: 26, spacing: 2)
                    }
                }
                cursor += 8
            }

            draw(
                "Generated by KWh Gas Companion. This is an owner-recorded inspection, not a Tesla document.",
                font: .systemFont(ofSize: 8.5),
                color: .gray,
                spacing: 0
            )
        }
    }

    /// PDF written to a temp file, ready for a share sheet.
    @MainActor
    static func pdfFileURL(_ run: DeliveryChecklistRun, store: DeliveryChecklistStore) -> URL? {
        let data = pdfData(run, store: store)
        let name = sanitizedFilename(run.displayTitle) + ".pdf"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(name)
        do {
            try data.write(to: url, options: [.atomic])
            return url
        } catch {
            return nil
        }
    }
}
#endif
